---
- hosts: all

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/apt.yml
      tags: apt
    - import_tasks: tasks/gnome.yml
      tags: gnome

  roles:
      - { role: protonmail-bridge, become: true, tags: protonmail-bridge }
      - { role: protonvpn, become: true, tags: protonvpn }
      - { role: docker, become: true, tags: docker }
      - { role: wireshark, become: true, tags: wireshark }
      - { role: gns3, become: true, tags: gns3 }
