---
- name: repository key
  ansible.builtin.apt_key:
    url: "https://downloads.sourceforge.net/project/zotero-deb/deb.gpg.key"

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb [by-hash=force] https://downloads.sourceforge.net/project/zotero-deb/ ./"

- name: installation
  ansible.builtin.apt:
    name: zotero
    state: present
