---
- name: repository key
  ansible.builtin.apt_key:
    url: "https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key"

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb https://github.com/retorquere/zotero-deb/releases/download/apt-get/ ./"
    filename: zotero

- name: installation
  ansible.builtin.apt:
    name: zotero
    state: present
