---
- name: keyring
  ansible.builtin.apt_key:
    url: "https://raw.githubusercontent.com/retorquere/zotero-deb/master/zotero-archive-keyring.gpg"
    keyring: "{{ zotero_keyring }}"

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ zotero_keyring }} by-hash=force] https://zotero.retorque.re/file/apt-package-archive ./"
    filename: zotero

- name: installation
  ansible.builtin.apt:
    name: zotero
    state: present
