---
- name: install software via apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packagelist }}"

- name: add additional software keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://packagecloud.io/AtomEditor/atom/gpgkey"
    - "https://packages.microsoft.com/keys/microsoft.asc"
    - "https://static.geogebra.org/linux/office@geogebra.org.gpg.key"
    - "https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key"

- name: Add repo for atom
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
    filename: atom
    state: present

- name: Add repo for teams
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"
    filename: teams
    state: present

- name: Add repo for geogebra
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://www.geogebra.net/linux/ stable main"
    filename: geogebra
    state: present

- name: Add repo for Zotero
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://github.com/retorquere/zotero-deb/releases/download/apt-get/ ./"
    filename: zotero
    state: present

- name: install additional software
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - atom
    - teams
    - geogebra-classic
    - zotero
