---
- name: get PKGBUILD
  ansible.builtin.set_fact:
    protonmail_bridge_PKGBUILD: "{{ lookup('url', 'https://protonmail.com/download/bridge/PKGBUILD') }}"

- name: get current version/release
  ansible.builtin.set_fact:
    protonmail_bridge_version: "{{ protonmail_bridge_PKGBUILD | regex_search('(?<=pkgver=).*?(?=,)') }}"
    protonmail_bridge_release: "{{ protonmail_bridge_PKGBUILD | regex_search('(?<=pkgrel=).*?(?=,)') }}"

- name: set package name
  ansible.builtin.set_fact:
    protonmail_bridge_package: "protonmail-bridge_{{ protonmail_bridge_version }}-{{ protonmail_bridge_release }}_amd64.deb"

- name: installation
  become: true
  become_user: root
  ansible.builtin.apt:
    deb: "https://protonmail.com/download/bridge/{{ protonmail_bridge_package }}"
