---
- name: repository key
  ansible.builtin.apt_key:
    url: "https://repo.steampowered.com/steam/archive/stable/steam.gpg"
    
- name: repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam"
    filename: steam

- name: installation
  ansible.builtin.apt:
    name: steam-launcher
    state: present
