---
- name: repository
  ansible.builtin.apt_repository:
    repo: ppa:wireshark-dev/stable

- name: prerequisites - debconf
  ansible.builtin.debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: 'true'
    vtype: select

- name: installation
  ansible.builtin.apt:
    name: wireshark
    state: present

- name: user to group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: wireshark
    append: true
