---
- name: keyring
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: "{{ docker_keyring }}"

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_keyring }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: installation
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: 0755

- name: user to group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: bashrc postgres
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PGHOST="localhost"'
  become: false
